version: "3.4"

x-env-variables: &common-variables
    INFLUXDB_DB: auo
    INFLUXDB_ADMIN_USER: root
    INFLUXDB_ADMIN_PASSWORD: ml6a01
    INFLUXDB_HTTP_AUTH_ENABLED: "false"
    TZ: Asia/Taipei
    
services: 
    web_application:

        restart: on-failure
        build: ./web
        container_name: web
        volumes: 
            - "$PWD/web:/code"
        ports:
            - "5000:5000"

        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        links:
            - rtsp_server
        networks:
            internal:
                ipv4_address: 172.30.1.3
        environment: *common-variables
    
    person_tracking:

        restart: on-failure
        build: ./person_tracking
        container_name: person_tracking
        volumes: 
            - "$PWD/person_tracking:/code"

        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        links:
            - rtsp_server
            - database
        ports:
            - "5555:5555"
        networks:
            internal:
                ipv4_address: 172.30.1.4
        environment: *common-variables
    
    rtsp_server:

        restart: on-failure
        build: ./rtsp_server
        volumes: 
            - "$PWD/rtsp_server/rtsp-simple-server.yml:/rtsp-simple-server.yml"
        ports:
            - "8554:8554"
        devices:
            - "/dev/video0:/dev/video0"
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"

        networks:
            internal:
                ipv4_address: 172.30.1.5
        environment: *common-variables
    
    redis:
        image: redis:7-alpine
        restart: always
        volumes:
            - "data:/usr/local/etc/redis"
        networks:
            internal:
                ipv4_address: 172.30.1.6
        ports:
            - "6379:6379"
    
    database:
        image: influxdb:1.8.10
        container_name: database
        # volumes: 
        #     - "data:/var/lib/influxdb"
        restart: always
        networks:
            internal:
        ports:
            - "8086:8086"
            - "8083:8083"
        environment: *common-variables
    
    grafana:
        image: grafana/grafana-oss:8.5.5
        restart: always
        networks:
            internal:
        ports:
            - 3000:3000
          
        
volumes:
    data:
    

networks:
    internal:
        ipam:
            driver: default
            config:
                - subnet: 172.30.0.0/16
